# Generated by Django 6.0.2 on 2026-02-25 20:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('acepta_notificaciones', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=15, unique=True)),
                ('rfid_tag', models.CharField(blank=True, help_text='ID del tag RFID de la llave', max_length=50, null=True)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('nivel_gasolina', models.FloatField(help_text='Porcentaje de 0 a 100')),
                ('ubicacion_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ubicacion_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('alerta_presion_neumaticos', models.BooleanField(default=False, help_text='True si el sensor TPMS detecta baja presión')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('alquilado', 'Alquilado'), ('taller', 'En Mantenimiento')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('vacaciones', 'Alquiler Vacacional'), ('traslado', 'Traslado Aeropuerto')], max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='flota.cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='flota.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='InspeccionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inspeccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('daños_detectados', models.BooleanField(default=False)),
                ('reporte_ia', models.TextField(blank=True, help_text='Descripción del daño generado por la IA (ej: Rayón puerta derecha)')),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='inspecciones/')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.reserva')),
            ],
        ),
    ]
